### ISSUE TITLE
ERROR:  null value in column "record_id" of relation "active_storage_attachments" violates not-null constraint

### ISSUE THREAD

**Issue by brentgreeff** [blocknotes/active_storage_db#27]
I am using your plugin with ActionMailbox,
I followed instructions in readme.

http://localhost:3000/rails/conductor/action_mailbox/inbound_emails/new
If I send an email in development

```log
[2023-01-25T17:05:46.419889 #79606] DEBUG -- :   ActiveStorage::Attachment Load (2.6ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", nil], ["record_type", "ActionMailbox::InboundEmail"], ["name", "raw_email"], ["LIMIT", 1]]
D, [2023-01-25T17:05:46.431688 #79606] DEBUG -- :   ActiveStorage::Attachment Create (7.8ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "raw_email"], ["record_type", "ActionMailbox::InboundEmail"], ["record_id", nil], ["blob_id", "85be5cc3-6e9b-4548-9d09-313dba0b7484"], ["created_at", "2023-01-25 16:05:46.423136"]]
D, [2023-01-25T17:05:46.435306 #79606] DEBUG -- :   TRANSACTION (1.6ms)  ROLLBACK
I, [2023-01-25T17:05:46.437930 #79606]  INFO -- : Completed 500 Internal Server Error in 274ms (ActiveRecord: 70.2ms | Allocations: 50127)


F, [2023-01-25T17:05:46.440553 #79606] FATAL -- :   
ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "record_id" of relation "active_storage_attachments" violates not-null constraint
DETAIL:  Failing row contains (78effb50-dd85-4101-9aed-4133cb9ccee7, raw_email, ActionMailbox::InboundEmail, null, 85be5cc3-6e9b-4548-9d09-313dba0b7484, 2023-01-25 16:05:46.423136).
):
  
activerecord (7.0.4.1) lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
activerecord (7.0.4.1) lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
activesupport (7.0.4.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
activesupport (7.0.4.1) lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
```

btw - this URL - /active_storage_db -does not seem to work.
and
`r 'asdb:list'`

produces

```log
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function max(uuid) does not exist
LINE 1: SELECT MAX("active_storage_blobs"."id") FROM "active_storage...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by brentgreeff** [comment]
I have rolled back your gem and I still get the error - seems like an issue with Rails - will confirm

**Comment by brentgreeff** [comment]
https://github.com/rails/rails/issues/44289
its a rails issue - sorry.
